spring:
  servlet:
    multipart:
      max-file-size: 10MB
      #总上传文件数大小
      max-request-size: 10MB
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true